name: Mail Security Monitor
slug: dmarc_monitor
description: DMARC monitoring for Home Assistant
version: "1.0"
startup: services
init: false
boot: auto
arch:
  - amd64
  - aarch64

options:
  imap_host: ""
  imap_user: ""
  imap_password: ""

schema:
  imap_host: str
  imap_user: str
  imap_password: password
